### ISSUE TITLE
Any recommended way of integrating with Java/Kotlin code in an .aar library

### ISSUE THREAD

**Issue by rib** [rust-mobile/cargo-apk#18]
Hi, I'm trying to determine if it makes sense to try and use cargo-apk vs rolling something more hacky/specific while I'm not currently sure how to be able to integrate with Java code that's packaged as an .aar library.

In my case I'd like to be able to package, deploy and test code that will eventually be deployed as part of a Unity 3D application where I have a rust plugin and I'd like to use JNI to access bluetooth apis on Android.

Notably the Unity build system can conveniently let me drop in an .aar library with my compiled/packaged Java code so ideally I'd like to be able to build + deploy my own rust-based test harness in a similar way with the Java code provided as an aar library. (The turn around when building directly with Unity is terrible so I'm looking for a way to more rapidly build and test things in development)

If cargo-apk could perhaps also drive building the aar library, or something similar via gradlew that could also be convenient. I imagine it would be asking too much for cargo-apk to be handling the actual compilation of java code and way out of scope to handle pulling in java dependencies.

Are there perhaps some example projects that aren't purely native that give some ideas for how to best manage pulling together more complex packages that are a mixture of both native and non-native code?

Is there perhaps some way that I can tell cargo-apk to please include a given .aar library?

**Comment by dvc94ch** [comment]
I think `cargo-apk` works great if you only rely on the `NativeActivity` and want to do your rendering in gl/vulkan. However if you want to integrate with custom java libraries or need to do things not supported with the `NativeActivity`, like services for example, I think `cargo-mobile` might be more appropriate. I think it allows you to build your rust code as a dynamic library and integrate it with the gradle/xcode build systems. (I haven't actually used cargo-mobile myself, so I might be mistaken)

NOTE: I'm also not particularly familiar with java so maybe it wouldn't be that hard to support

**Comment by rib** [comment]
Okey, thanks for the pointer I should take a look.

I'm not really experienced with java dev either but just thinking about supporting Java compilation I do recall using Meson a few years ago with an Android project which did try and handle compiling java for us too. I think the issue there isn't really with how difficult it is to compile the java code itself (relatively simple) - the bigger problem is that you quickly realise that you need to interact with Maven repos and such to download various dependencies for anything beyond a Hello World test and then things quickly get out of hand and so in practice I think you kinda end up forced to use something like Gradle to deal with the non-native side of things without really trying to boil the ocean - which is a shame since Gradle is a monster :/

My current thinking is that I guess I'll use Gradle to at least build the non-native side of things into an .aar library and then I'm hoping I can find a neat way of building/packaging/deploying a simple test harness for my plugin.

Maybe cargo-mobile is more along the lines of what I need I'll check it out, thanks again.

**Comment by iamralpht** [comment]
We recently did this in our project, so it's definitely possible! Initially we used `cargo apk` to build our shared objects from a gradle task, and then copy them into `libs/` prior to task that creates the AAR. We switched to using [Mozilla's rust-android-gradle](https://github.com/mozilla/rust-android-gradle) which does pretty much the same thing as shelling out to `cargo apk` did (and we still use `ndk_glue`; it doesn't care which build tool is used).

We're also using Java code with Rust, and we achieve that by using the JNI crate to register native functions (implemented in Rust) and to call Java code from Rust. So nothing in these crates (ndk, ndk-glue, etc) prevents nice interop with Java, and you can certainly use Java to provide an Android-ish API for your Rust code. You can also distribute your AAR containing Rust binaries via Maven so downstream projects from you can incorporate your library via gradle, too.

**Comment by Animeshz** [comment]
@iamralpht have you got any example of the shift? Interested but don't know where to start.

Also, is your app more like kotlin/java based and rust is glued into it?

And, how is rust's main() is called? `System.loadLibrary()`?

**Comment by iamralpht** [comment]
@Animeshz our Rust code exports a `JNI_OnLoad`, and that gets called via `System.loadLibrary` -- so it's just the same as a JNI shared object you'd write in C.

**Comment by rib** [comment]
So when I first opened this, I wasn't yet familiar with the scope of `cargo-apk` or `ndk-glue` etc and I think this was probably more a question of looking for an ideal toolchain that would make it easy to build apks based on a standalone native Rust application that was also utilizing Java/Kotlin code in an `.aar` library.

In the end I went with using a combo and `cargo ndk` and `Gradle`, since (at least at the time) I didn't find any mature tooling that could deal with both Rust and Java code (I tried mozilla's gradle plugin but hit bugs and also didn't want to use Gradle any more than strictly necessary)

I guess I originally opened this against `ndk-glue` and that's why @dvc94ch moved this to this repo, but maybe I should have originally opened it against `cargo apk`.

It's possible that `xbuild` can help with this now - I still need to get a chance to look at `xbuild` more closely.

Either way though I think it makes sense to close this issue now. It's not really an issue with `android-activity`

**Comment by MarijnS95** [comment]
> I guess I originally opened this against `ndk-glue` and that's why @dvc94ch moved this to this repo, but maybe I should have originally opened it against `cargo apk`.

Both were in the same repo back then, maybe it shouldn't have been transferred from `android-ndk-rs` to `android-activity` but `cargo-apk` instead (as you ask about supporting this in `cargo-apk` in the OP)?

**Comment by MarijnS95** [comment]
Transferred to `cargo-apk`; @rib do you think it's worth reopening? `xbuild` supports AAB but not AAR yet, and since the "deprecation" of `cargo-apk` it is perhaps worth transferring or re-asking this question in `xbuild`?

**Comment by rib** [comment]
At this point it seems like `xbuild` might be the place to ask the same kind of question if you figure that it's out of scope for `cargo apk`

I suppose from my perspective atm I don't feel like I have the same question any more and am happy enough to close the issue.

It could make sense to ask a similar question in `xbuild` but at least atm I don't have concrete requirements for needing to use an `.aar` so it probably shouldn't come from me.

Being able to pull in java deps via a Maven repo (both local or remote) sounds like the right general direction.

It would be good to do a case study of how we can build / maintain utility crates (similar to `app_dir2` or `bluey`) that may want to have supporting Java code that's invoked via JNI. These projects should ideally be able to publish the java package via Maven Central or Github package registry (or a convention of building and placing in a local Maven repo) and it should be straight forward to pull those in when building an application that uses these utilities.

**Comment by MarijnS95** [comment]
Fwiw `app_dirs2` is simple enough to get away with a few JNI calls to existing Android methods, no Java functionality required.

**Comment by rib** [comment]
> Fwiw `app_dirs2` is simple enough to get away with a few JNI calls to existing Android methods, no Java functionality required.

yeah - was more of a conceptual reference. I didn't double check but had a feeling that was the case.

I was recently considering creating a utility crate to help with requesting Android permissions which might be another example. For that I think it will be helpful to have a small support library written in Java/Kotlin that would be used via JNI, hidden behind a Rust API.

**Comment by MarijnS95** [comment]
And it looks like someone just created a utility crate for `Intent`s too, should those be folded together? As discussed elsewhere it'd be great to have Rust crates that may come with some additional precompiled `.class` files that can be loaded by JNI to support additional features that are too complex to write purely in Rust with JNI.

**Comment by rib** [comment]
I think like `app_dirs2` that crate didn't need a support library, afik (https://github.com/concoct-rs/android-intent-rs) - though maybe it could be simplified if it did have a Java support library.

I didn't quite follow what your asking with:

> should those be folded together?


Experimenting briefly the other day with how to deal with the Java support code in Bluey I looked at adding CI support for publishing the Java code to a Github Maven repo like this: https://github.com/rib/bluey/packages/1786906 (ref: https://github.com/rib/bluey/blob/c0edc05d802a34334b4eef8ba71baf3cdcac3a03/.github/workflows/ci.yml)

Maven is probably the most standard way of publishing Java packages so that seems like a reasonable general approach but a really annoying issue with using Github's Maven support is that you can only download from those repos if you have set up a Personal Access Token with permission to read packages (even for public repos). That's _possibly_ acceptable, considering that it's a much bigger hassle to publish to Maven Central but it's certainly not ideal.

What I was going to look at next was instead just relying on a local maven repo (Gradle's `maven-publish` plugin also makes it easy to build artifacts that go into a local maven repo) and it could make sense if `xbuild` would be compatible with that approach.

**Comment by MarijnS95** [comment]
> though maybe it could be simplified if it did have a Java support library.

Don't see the need for this, it's simple enough and already existing, tested and working.

> I didn't quite follow what your asking with:
> 
> > should those be folded together?

To merge intent utilities with any other utilities you have in mind, sharing part of the code?

At the very least we should host all these under @rust-mobile.

---

All the rest about `mvn` sounds cool but not something I have experience with yet. `xbuild` contains `mvn` support in some form so this might well be designed with that use-case in mind, as long as Rust crates themselves can describe (via package metadata, perhaps) what packages they need and have `xbuild` fetch/provide them on build.

**Comment by rib** [comment]
> > though maybe it could be simplified if it did have a Java support library.
> 
> Don't see the need for this, it's simple enough and already existing, tested and working.

👍


> > I didn't quite follow what your asking with:
> > > should those be folded together?
> 
> To merge intent utilities with any other utilities you have in mind, sharing part of the code?

Ah, right. That's up to @matthunz really. Having a clear scope (utilities related to `Intents`) is probably good though instead of piling in too much miscellaneous stuff. I guess if we see there's lots of repetition happening between these kinds of crates we can think about that later but I wouldn't worry about it up front.

It's probably not too bad if we end up with quite a few small utility crates that each have a clear purpose. That will make it easier to deprecate / refactor / replace crates in situations where initial ideas don't work out and minimize churn downstream if each crate is orthogonal.

> At the very least we should host all these under https://github.com/rust-mobile.

Having more of these kinds of crates under `rust-mobile` could be nice so that we can:
1. make them a little easier to discover
2. more easily share ideas / patterns between them where it makes sense. There are few cross-cutting issues we have that we haven't got good answers for yet (e.g. dealing with libc++ static/shared linking, or dealing with Android SDK versioning, or ndk-context etc) where it could be good to collaborate on solving these things consistently.
3. share the maintenance burden in case of crates that don't need much active development

**Comment by matthunz** [comment]
I'd love to merge my crate in! I started a PR for it here if you're into it https://github.com/rust-mobile/android-activity/pull/63
