### ISSUE TITLE
Example showing how to request for permissions

### ISSUE THREAD

**Issue by charleschege** [rust-mobile/cargo-apk#19]
Is there an example showing how to request for example `STORAGE` permissions using jni and ndk-context like:

```rs
let ctx = ndk_context::android_context();
    let vm = unsafe { jni::JavaVM::from_raw(ctx.vm().cast()) }.unwrap();
    let context = unsafe { JObject::from_raw(ctx.context().cast()) };
    let env = vm.attach_current_thread().unwrap();

    // Query the global Audio Service
    let class_ctx = env.find_class("android/content/Context").unwrap();
    let storage_service = env
        .get_static_field(class_ctx, "AUDIO_SERVICE", "Ljava/lang/String;")
        .unwrap();

    let storage_manager = env
        .call_method(
            context,
            "getSystemService",
            "(Ljava/lang/String;)Ljava/lang/Object;",
            &[storage_service],
        )
        .unwrap()
        .l()
        .unwrap();

    // Request storage permission
    let permission_read = env
        .new_string("android.permission.READ_EXTERNAL_STORAGE")
        .unwrap();
    let permission_write = env
        .new_string("android.permission.WRITE_EXTERNAL_STORAGE")
        .unwrap();

env.call_method(
        storage_manager,
        "requestPermissions",
        "([Ljava/lang/String;I)V",
        &[
            permission_read.into(),
            JValue::from(permission_request_code),
        ],
    )
    .unwrap();
```

With the strict Rust types enforced  it can be difficult to know exactly what to do and  where the errors occured like the example above results in error:
```sh
02-20 12:35:17.831 15654 15693 I RustStdoutStderr: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JavaException', src/lib.rs:66:6
02-20 12:35:17.831 15654 15693 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Which doesn't say much.

**Comment by MarijnS95** [comment]
@charleschege That indeed doesn't say much, as we don't know which line in your example corresponds to line `66` in `lib.rs` :)

**Comment by charleschege** [comment]
Sorry about that.

Its
```rs
permission_read.into(),
```

**Comment by charleschege** [comment]
An example to show how to request for permissions would be more ideal though.

Like the audio example is well done

**Comment by MarijnS95** [comment]
Right, yes, you are calling `requestPermissions` on the `storage_manager` variable which contains https://developer.android.com/reference/android/media/AudioManager (from the string `AUDIO_SERVICE`), it doesn't have that method :)

EDIT: Neither does https://developer.android.com/reference/android/os/storage/StorageManager, I think that method has to be called on an `Activity`/`AppCompatActivity`?

**Comment by charleschege** [comment]
Sorry I missed that while copy pasting. 

Changing it to STORAGE_SERVICE, still same error

**Comment by MarijnS95** [comment]
> Changing it to STORAGE_SERVICE, still same error

Again, as mentioned above `requestPermissions` doesn't exist on `StorageManager` either. Perhaps you're interested in reading https://github.com/matthunz/permissions / https://github.com/rust-mobile/android-activity/issues/66? Feel free to converse there, this issue has nothing to do with `cargo-apk` (aside from borrowing a few lines from a runtime example) so I'll close it.

**Comment by charleschege** [comment]
Thanks for pointing me to the permissions repo

**Comment by iincity** [comment]
> Thanks for pointing me to the permissions repo
this code can not buid for me:

error[E0308]: mismatched types
   --> src\lib.rs:217:15
    |
217 |             &[storage_service],
    |               ^^^^^^^^^^^^^^^ expected `JValueGen<&JObject<'_>>`, found `JValueGen<JObject<'_>>`
    |
    = note: expected enum `JValueGen<&jni::objects::JObject<'_>>`
               found enum `JValueGen<jni::objects::JObject<'_>>`
