### ISSUE TITLE
How can I modify the AndroidManifest.xml

### ISSUE THREAD

**Issue by VZout** [rust-mobile/cargo-apk#25]
I want to modify the AndroidManifest.xml. Is there a existing way to add permissions for example?

**Comment by dvc94ch** [comment]
Same as cargo-apk. The Cargo.toml should be compatible. I don't recall if to 100% or if some small changes need to be made.
I'd suggest looking at the code as documentation is lacking. The code is very straightforward.

**Comment by VZout** [comment]
Thanks!

**Comment by anoushk1234** [comment]
> Thanks!

Hey @VZout did you figure this out? for some reason android is blocking my network requests and apparently i need to add `<uses-permission android:name="android.permission.INTERNET"/>` acc to this [SO post](https://stackoverflow.com/a/55548864/13749032)

**Comment by VZout** [comment]
It's been a while since i've touched android but we use cargo-apk which allows us to write

```
[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"
```

in the cargo.toml file. cargo-apk has some good documentation on it.

**Comment by MarijnS95** [comment]
`cargo-apk` manifest docs: https://github.com/rust-mobile/cargo-apk/blob/main/cargo-apk/README.md#manifest

`xbuild` has a similar mechanism via `manifest.yaml`, but we don't have any docs for it besides a far-too-minimal example: https://github.com/rust-mobile/xbuild/blob/master/xbuild/template/manifest.yaml. This also supports the whole manifest supported by `cargo-apk`.
