### ISSUE TITLE
Distribute pre-built binaries for cargo-apk

### ISSUE THREAD

**Issue by notgull** [rust-mobile/cargo-apk#31]
At the moment, `winit`'s CI pipeline [builds or caches a fresh copy of `cargo-apk`](https://github.com/rust-windowing/winit/blob/1dfca5a395dda90968809a562e87f5488ebc545b/.github/workflows/ci.yml#L89-L100) for Android. It would be cleaner to instead just install the binary through [`install-action`](https://github.com/taiki-e/install-action) or [`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall).

However, `cargo apk` does not distribute binaries that can be installed. It would be better if pre-built binaries of `cargo-apk` were distributed through GitHub Actions, so that they can be easily installed by users.

See [here](https://github.com/taiki-e/cargo-llvm-cov/blob/main/.github/workflows/release.yml) for an example of how this can be done automatically through a release pipeline. I am willing to write the CI code, but I need cooperation from a @rust-mobile admin to handle setting up secret keys.

**Comment by MarijnS95** [comment]
`cargo-apk` has been deprecated some years ago in favour of `xbuild`, so I don't think I would spend time engineering such a thing. There isn't even enough time to get `xbuild` on-par with `cargo-apk` in certain areas.

**Comment by notgull** [comment]
> `cargo-apk` has been deprecated some years ago in favour of `xbuild`,

Hmm, I wasn't aware of this. It should probably be signaled better in this repository, as `winit` still uses it in CI.

**Comment by MarijnS95** [comment]
It looks like it got "lost" (or rather, not a purpose-made one added) when this repo was split out from the main `ndk`/`android-ndk-rs` repo.
