### ISSUE TITLE
NDK 16 throws os error 2

### ISSUE THREAD

**Issue by p0ryae** [rust-mobile/cargo-apk#38]
I'm using NDK r16b since it is the last ndk that actually supports armv6 architecture, but using it with cargo-apk throws the following error:
```
Error: No such file or directory (os error 2)
```

Can't really find the root of this problem via the source code either. It's very vague.

**Comment by p0ryae** [comment]
**Update:**

The lack of  `build/core/platforms.mk` for NDK 16 is causing this issue. I created the file and wrote the following for it (Lower NDK versions might need different values for min/max platform level):
```
NDK_MIN_PLATFORM_LEVEL := 14
NDK_MAX_PLATFORM_LEVEL := 27
```

**Comment by MarijnS95** [comment]
I wonder if you might be able to use the host `clang` compiler instead, maybe it still has support for armv6?

`xbuild` uses the host compiler, with only minimal bits from the NDK.
