### ISSUE TITLE
Modifying the -std flag for clang++

### ISSUE THREAD

**Issue by p0ryae** [rust-mobile/cargo-apk#39]
I want to change the `-std=c++17` flag that gets passed through the clang++ llvm to `-std=c++1z`, since I'm using an older NDK (r16b). The following error crashes my build otherwise:

```
Compiling oboe-sys v0.5.0
The following warnings were emitted during compilation:

cargo:warning=errorerror: invalid value 'c++17' in '-std=c++17'

  error occurred: Command "/home/porya/Android/Sdk/ndk/16.1.4479499/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" "-O3" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "--target=arm-linux-androideabi" "-static" "--target=arm-linux-androideabi23" "-I" "oboe/include" "-I" "oboe/src" "-I" "oboe-ext/include" "-I" "oboe-ext/src" "-std=c++17" "-Wall" "-Wextra-semi" "-Wshadow" "-Wshadow-field" "-fno-rtti" "-fno-exceptions" "-DOBOE_ENABLE_LOGGING=1" "-o" "/home/porya/Github/trs_24/target/arm-linux-androideabi/debug/build/oboe-sys-7626711f30a4069e/out/library/oboe-ext/src/AudioStreamCallbackWrapper.o" "-c" "oboe-ext/src/AudioStreamCallbackWrapper.cpp" with args "clang++" did not execute successfully (status code exit status: 1).
```

Any ideas?

**Comment by p0ryae** [comment]
Fixed by excluding the feature requiring oboe-sys dependency (`bevy_audio` in my case). 

Although now there is no longer audio support for the engine. 

Likely will open an issue directly in oboe-rs later.

**Comment by MarijnS95** [comment]
`cargo-apk` doesn't set these flags as you found out, that is up to individual crates using the provided cross-compiler (via env vars set up by `cargo-apk`), typically through the `cc` crate.

It is unlikely that `oboe` will compile without this flag: they must have set it for a reason, i.e. the native code using C++17 features. Perhaps you'll have to use an older version, or features have to be gated on their end.
