### ISSUE TITLE
Where is the documentation for how to set `AndroidManifest.xml` elements?

### ISSUE THREAD

**Issue by eribol** [rust-mobile/cargo-apk#49]
I am using slint and cargo-apk for a simple example. I tried use request but it always gives PermissionDenied error. I wanted to change Androidmanifest.xml but i do not know where cargo-apk look for it or how can i change it.

**Comment by MarijnS95** [comment]
Fortunately, unlike `xbuild`, `cargo-apk` already has documentation for every manifest field that it supports right in the root of the crate documentation:

https://crates.io/crates/cargo-apk
https://github.com/rust-mobile/cargo-apk/tree/main/cargo-apk#manifest
